stages:
  - code-quality
  - pre-deploy
  - deploy

markdown_lint:
  stage: code-quality
  tags:
    - linux
  image: pipelinecomponents/markdownlint:6ff4ccf
  script:
    - mdl --style all --warnings .

yaml_lint:
  stage: code-quality
  tags:
    - linux
  image:
    name: cytopia/yamllint:1.20
    entrypoint:
      - env
  script:
    - yamllint .gitlab-ci.yml

helm_lint:
  stage: code-quality
  image:
    name: lachlanevenson/k8s-helm:v3.2.4
    entrypoint: [""]
  script:
    - helm lint helm/
